---
# Eucalyptus Cloud playbook - Step by Step setup
#

- hosts: all
  roles:
  - JohnPreston.eucalyptus-network
  - JohnPreston.eucalyptus-setup
  vars:
  - networking_mode:

- hosts: all
  roles:
  - JohnPreston.eucalyptus-initialize
  - JohnPreston.eucalyptus-register
  - JohnPreston.eucalyptus-start
  vars:
  - networking_mode:
  vars_files:
  - vars/availability_zones.yml

- hosts: clc
  roles:
  - JohnPreston.eucalyptus-configure
  vars:
  - networking_mode:
  - osg_provider: walrus
  vars_files:
  - vars/availability_zones.yml
